一些小東西
RedenMC/reden-website pull request #13
Opened 2024-04-26 09:11 UTC by SmallSun697

1. 拉桿動畫調整

2. ![image](https://github.com/RedenMC/reden-website/assets/122592594/5fe55ecf-0664-484a-a816-3fb1d822a6e7)

    新增background-color

3. https://github.com/zly2006/reden-is-what-we-made -> githubLink

2024-04-26 09:12 UTC, SmallSun697 commented
我感覺你會需要 @zly2006

2024-04-26 09:15 UTC, zly2006 requested changes
https://github.com/RedenMC/reden-website/blob/403649f5195d79739879b5e3653d30b6158ae00c/src/layouts/default/Default.vue#L9-L13

那这里就不需要了，请删掉这的代码吧

2024-04-26 09:27 UTC, zly2006 approved these changes

2024-04-26 09:27 UTC, merged

2024-04-26 11:54 UTC, SmallSun697 commented
> https://github.com/RedenMC/reden-website/blob/403649f5195d79739879b5e3653d30b6158ae00c/src/layouts/default/Default.vue#L9-L13
> 
> 在这里已经设置了，删掉你写的background color吧，这样可以同时兼容黑白主题

我知道這東西的存在 但他也許不起作用? 每次網頁載入的時候都閃瞎我的眼 ⬜👀

2024-04-29 00:49 UTC, SmallSun697 commented
為什麼拉桿動畫還是原本的樣子🤔

2024-04-29 05:14 UTC, zly2006 commented
> 為什麼拉桿動畫還是原本的樣子🤔

idk，你要不debug一下？还有你看的是哪里？https://redenmc.com 还没有更新

2024-04-29 12:13 UTC, SmallSun697 commented
> > 為什麼拉桿動畫還是原本的樣子🤔
> 
> idk，你要不debug一下？还有你看的是哪里？https://redenmc.com 还没有更新

那沒問題了 github的有更改 伺服器沒更新