佈局更新
RedenMC/reden-website pull request #7
Opened 2024-04-15 07:40 UTC by SmallSun697

main-page,Feature 佈局更動
background-color,appbar,淺色主題 更動
Reden,FeatureTitle 圖標變更
Undo,RVC,Debugger 圖標新增
RedstoneSectionTitle 拉桿動畫更動
(部分響應式

2024-04-17 11:02 UTC, zly2006 commented
Resolve conflicts please

2024-04-19 16:21 UTC, Cubik65536 requested changes
Please resolve all the git conflicts.

2024-04-23 13:58 UTC, zly2006 commented
请解决冲突，在[github](https://github.com/RedenMC/reden-website/pull/7/conflicts)或者本地git，然后记得运行一遍yarn install

2024-04-23 14:32 UTC, SmallSun697 commented
🤔應該行了:)

2024-04-23 14:35 UTC, zly2006 commented
> 🤔應該行了:)

<img width="884" alt="image" src="https://github.com/RedenMC/reden-website/assets/66198935/25df1392-47d4-409e-b5a4-9cdf274b85e4">

🤔

2024-04-23 15:14 UTC, zly2006 commented
我个人感觉你的PR中新添加的图标并不太好看，但是我也不太好说怎么改。其他的话布局我还没看，等自动部署了看看吧

@TM-SunnyDay 希望你的意见

2024-04-23 15:26 UTC, zly2006 commented
还有一点我在考虑，要不要尝试引入vercel来帮助测试前端？这么做的缺点是只有前端，没法做更多地测试

2024-04-23 15:28 UTC, zly2006 commented
<img width="1624" alt="image" src="https://github.com/RedenMC/reden-website/assets/66198935/64dfca5c-0c09-4dd4-b914-77022669265d">
感觉这多少有点炸裂了……

2024-04-23 15:54 UTC, zly2006 commented
请同步upstream，这样的话ci就可以通过了

还有，能不能说说你是以什么理念设计页面的？

2024-04-24 18:09 UTC, zly2006 commented
指出一点：之前可以鼠标点击红石灯，实现拉杆动画和开关灯，你似乎没做

2024-04-24 18:16 UTC, Cubik65536 commented
> [reden-website-git-vercel-preview-redenmc.vercel.app](https://reden-website-git-vercel-preview-redenmc.vercel.app/)
> 
> @Cubik65536 vercel preview here, so you dont need to pull the source :D

I can't view preview lol, they restricted access for people not in the same Vercel team... I'll test it locally then.

2024-04-24 18:19 UTC, zly2006 requested changes

2024-04-24 18:19 UTC, zly2006 commented on public/feature/RVC.png
中心偏左，建议别改

2024-04-24 18:19 UTC, zly2006 commented on public/feature/Undo.png
颜色单一

2024-04-24 18:19 UTC, zly2006 commented on src/components/FeatureSectionTitle.vue
> +            lampOn.value = true;
点击切换开关灯被删除了，请解释原因？

2024-04-24 18:29 UTC, zly2006 commented on public/feature/Undo.png
还有你的指针为什么两像素宽，我感觉有点丑，如果你不擅长画像素风用普通的风格也ok

2024-04-24 18:45 UTC, Cubik65536 commented
Vercel Teams 只有 14 天免费，你得部署到你私人的库里（应该） @zly2006 
另外我这里拉杆开关红石灯是可以的啊

我整体不觉得有啥大问题

2024-04-24 18:54 UTC, zly2006 commented
> Vercel Teams 只有 14 天免费，你得部署到你私人的库里（应该） 

管他，不能用了再说（逃
> 另外我这里拉杆开关红石灯是可以的啊

啊？我都没有看见click逻辑，你是在看pr分支还是主分支

2024-04-24 19:58 UTC, Cubik65536 commented
> > Vercel Teams 只有 14 天免费，你得部署到你私人的库里（应该） 
> 
> 
> 
> 管他，不能用了再说（逃
> 
> > 另外我这里拉杆开关红石灯是可以的啊
> 
> 
> 
> 啊？我都没有看见click逻辑，你是在看pr分支还是主分支
> 
> 

我在看你 issue comment 发给我的那个链接，有 git-preview 的那个

2024-04-25 07:37 UTC, zly2006 commented
> > 啊？我都没有看见click逻辑，你是在看pr分支还是主分支
> 
> 我在看你 issue comment 发给我的那个链接，有 git-preview 的那个

是features不是community部分，community部分没改，你看看代码，lampOn这个ref根本就没被使用……

2024-04-25 07:42 UTC, zly2006 commented
> <img alt="image" width="1624" src="https://private-user-images.githubusercontent.com/66198935/324896081-64dfca5c-0c09-4dd4-b914-77022669265d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzA4NjcsIm5iZiI6MTcxNDAzMDU2NywicGF0aCI6Ii82NjE5ODkzNS8zMjQ4OTYwODEtNjRkZmNhNWMtMGMwOS00ZGQ0LWI5MTQtNzcwMjI2NjkyNjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA3MzYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YmI5ZmYwZjYyNGQxNGFlYjJkMTc5NmE0NDdhMDEyODMyODU3MGIwN2JjMGEwYzE4NWYwMjNmYTg4NDU3MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5El2RjnQAG1q4SwJHhHTyOhs9HuYbxytDWnERuTRbrM"> 

还有，首页真的必须改，如果你要把苹果作为icon，但是苹果只在最左边20%出现。 @SmallSun697 
介绍也在最右边。
这两个一个是门面一个是信息主体，不应该放在中间的位置吗？

随便找个官网首页抄，我想都不会设计成这个样子

fyr:
https://visualstudio.microsoft.com/zh-hans/
https://www.jetbrains.com/idea/

2024-04-25 07:43 UTC, zly2006 commented
我觉得你可以把zh-tw的翻译单独拿出来另发一个PR，现在你这个布局确实不是很符合我的意愿，不太可能被merge。

当然，如果你有足够的理由可以说服我也可

2024-04-25 07:45 UTC, zly2006 commented
> 随便找个官网首页抄，我想都不会设计成这个样子
> 
> fyr: https://visualstudio.microsoft.com/zh-hans/ 
> ...

vs这里的动图我们可以放一个YouTube/bilibili的视频，但是我真的懒得剪视频，摆

2024-04-25 07:51 UTC, zly2006 commented
> 我是覺得和原本的差不多 我第一個注意到的是下載按鈕 所以我把下載按鈕做在中間

@SmallSun697 毫无疑问，下载应该在中间，但是我说的是 **icon 和 description **，也应该在视觉中心，边上应该放上宣传图或者宣传视频

2024-04-25 07:52 UTC, zly2006 commented
> 那card你覺得怎麼樣?

我觉得改的还不错，但是具体的细节还需要再看看

在GitHub交流不好嘛QaQ

2024-04-25 07:56 UTC, zly2006 commented
> 我是覺得宣傳影片放下方 當底

懂不懂什么叫图片才能一下子抓住人的眼睛？多媒体资源能很好的帮助人们了解reden

2024-04-25 07:58 UTC, SmallSun697 commented
？

2024-04-25 08:00 UTC, SmallSun697 commented
所以是指你希望完全不認識reden的人能只看home page就了解reden是什麼的意思?

2024-04-25 08:12 UTC, zly2006 commented
如果看了home page还不知道reden解决了什么问题有什么作用，那这个官网肯定是失败的

> 2024年4月25日 16:01，SmallSun697 ***@***.***> 写道：
> 
> 
> 所以是指你希望完全不認識reden的人能只看home page就了解reden是什麼的意思?
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/RedenMC/reden-website/pull/7#issuecomment-2076600227>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/APZB3FZXUMW2WPMWIGDCC4TY7CZ3ZAVCNFSM6AAAAABGGZOESKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANZWGYYDAMRSG4>.
> You are receiving this because you were mentioned.
>

2024-04-25 08:16 UTC, SmallSun697 commented
痾 這麼說吧 這官網是寫給誰看的?
(其實我覺得那簡介寫的很糟

2024-04-25 08:22 UTC, zly2006 commented
“官网是给谁看的”，这个问题您应该Google而不是在这个PR里问

觉得写得不好你可以改，而且你应该说明理由

> 2024年4月25日 16:16，SmallSun697 ***@***.***> 写道：
> 
> 
> 痾 這麼說吧 這官網是寫給誰看的?
> (其實我覺得那簡介寫的很糟
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/RedenMC/reden-website/pull/7#issuecomment-2076627196>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/APZB3F74AJALLXSCPPRO5LDY7C3VVAVCNFSM6AAAAABGGZOESKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANZWGYZDOMJZGY>.
> You are receiving this because you were mentioned.
>

2024-04-25 08:31 UTC, SmallSun697 commented
> 为红石机器开发者提供一站式工作环境，成为最好的红石调试和教学工具。
我得到的資訊是
1給紅石機器開發者使用
2一站式(這個我不懂
3兩個功能(紅石調適和教學工具
僅限紅石開發者? 教學工具是指debugger嗎?

2024-04-25 08:33 UTC, SmallSun697 commented
你是想寫給不知道reden的人 還是知道reden的人

2024-04-25 08:37 UTC, zly2006 commented
home page肯定是给不知道的人看啊，home page、tutorial和document/wiki有各自不同的用处……

> 2024年4月25日 16:34，SmallSun697 ***@***.***> 写道：
> 
> 
> 你是想寫給不知道reden的人 還是知道reden的人
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/RedenMC/reden-website/pull/7#issuecomment-2076657853>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/APZB3F7MOEVZXUTC7XY3WKTY7C5XZAVCNFSM6AAAAABGGZOESKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANZWGY2TOOBVGM>.
> You are receiving this because you were mentioned.
>

2024-04-25 08:39 UTC, SmallSun697 commented
那下載就沒有那麼重要了

2024-04-25 08:46 UTC, zly2006 commented
请原谅我的耐心已经耗尽。

你的话语中充斥着清澈的愚蠢，你见过谁家模组官网下载不重要的？用户就不能看了我们的介绍下载体验吗？你哪怕多看几个工具类软件/模组的官网呢？哪有这么设计的？？你难不成还要加一个cookie，如果用户访问过网站就不给他提供下载链接了？你是怎么想的？？

2024-04-25 09:02 UTC, SmallSun697 commented
所以你是希望一個窗口內包含icon 名稱 簡介 下載 影片 所有東西(影片除外)都盡可能的放在中間?

我所謂的不重要是指下載不是最優先 這網站是寫給不認識reden的人 第一件事是了解這是什麼 而不是下載

所以不該把下載放最中間

2024-04-25 09:08 UTC, zly2006 commented
请把zh-tw的翻译单独发一个PR，然后参照其他软件的官网修改好你的布局

2024-04-25 09:08 UTC, closed without merging

2024-04-25 09:11 UTC, SmallSun697 commented
也許是我表達的不夠好 不重要是指跟名稱 icon比起來相對不重要

我也覺得下載很重要 所以我有在bar的reden的右邊加上了下載按鈕

2024-04-25 09:19 UTC, SmallSun697 commented
icon放左邊是因為他有顏色 能夠吸引注意力 所以我覺得放哪都沒問題
Reden我放在了接近正中間的位置
下載是因為原本你用了藍色 所以我覺得他是非常重要的比介紹還重要 所以放在中間下面
介紹因為左邊有icon 所以放到了右邊 當畫面寬度不足的時候放到下面

2024-04-25 09:19 UTC, SmallSun697 commented
icon放左邊是因為他有顏色 能夠吸引注意力 所以我覺得放哪都沒問題
Reden我放在了接近正中間的位置
下載是因為原本你用了藍色 所以我覺得他是非常重要的比介紹還重要 所以放在中間下面
介紹因為左邊有icon 所以放到了右邊 當畫面寬度不足的時候放到下面

2024-04-25 09:21 UTC, zly2006 commented
睁大你的眼睛，仔细看看https://www.jetbrains.com/idea/

你看下载按钮在哪里？

考虑到reden没有icon的视觉图，右上角可以不用这么大，留出空间给宣传图/视频

你真的觉得你设计的很好看吗？谁家正文在标题右边而不是下边？？？？你给我找这个一个网站去，ok？

不会设计可以抄，蓝色是theme color你可以改的啊大哥，我真绷不住了

2024-04-25 09:21 UTC, SmallSun697 commented
如果介紹和下載換個位置你覺得怎麼樣

2024-04-25 09:23 UTC, zly2006 commented
> 如果介紹和下載換個位置你覺得怎麼樣

糟糕透顶，我想问原来的布局哪里不好了？你改icon我还能理解，改介绍按钮干什么？

2024-04-25 09:45 UTC, SmallSun697 commented
繁中開一個pr
appbar你要嗎?
card你要嗎?

2024-04-25 10:25 UTC, zly2006 commented
先参照其他软件的官网修改好你的布局再说

2024-04-25 10:46 UTC, zly2006 commented
其实card分栏是比较正确的排版，但是我还没想好怎么和现有的红石元素融合

2024-04-25 10:52 UTC, SmallSun697 commented
分栏?

標題 icon那些我不動了 照原本的 我的改這個你要留什麼跟我說 其他我不改了

2024-04-25 10:59 UTC, zly2006 commented
> 分栏?
> 
> 標題 icon那些我不動了 照原本的 我的改這個你要留什麼跟我說 其他我不改了

如果这样的话，您有没有兴趣实现一个新特性呢？就是Explore界面，让用户发现新机器

2024-04-25 11:44 UTC, SmallSun697 commented
我不太理解你想做什麼

2024-04-25 11:55 UTC, SmallSun697 commented
> > 分栏?
> > 
> > 標題 icon那些我不動了 照原本的 我的改這個你要留什麼跟我說 其他我不改了
> 
> 如果这样的话，您有没有兴趣实现一个新特性呢？就是Explore界面，让用户发现新机器

這是我弄的你沒一個要的意思嗎 👀

2024-04-25 14:01 UTC, Cubik65536 commented
恭喜你学到了重要的一课：在没有充分讨论之前不要做大改的东西，否则极有可能你的工作是白费的

2024-04-25 14:25 UTC, zly2006 commented
> 這是我弄的你沒一個要的意思嗎 👀

card有一点吧，我更喜欢想idea那样两列带图的格式

2024-04-26 00:11 UTC, SmallSun697 commented
> 
> > 這是我弄的你沒一個要的意思嗎 👀
> 
> card有一点吧，我更喜欢想idea那样两列带图的格式

能說的具體一點嗎 card的外框? 還是啥